
# Use Node.js 20 as the base image
FROM node:20 AS base 

# Set the working directory
WORKDIR /app


# Copy package.json and package-lock.json
COPY package.json package-lock.json  ./

# Install dependencies using npm
RUN npm install --force

# Copy the rest of the application code
COPY . .  

# Build the application using npm
RUN npm  run  build  

# Use Node.js 20 Alpine as the release image
FROM node:20-alpine3.19 AS release

# Set the working directory
WORKDIR /app 


# Copy node_modules, package.json, and built files from the base image
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next

# Expose port 3000
EXPOSE 3000

# Start the application using npm
CMD ["npm", "start"]